package hibernate;
// Generated 21/10/2016 21:23:46 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Alerta generated by hbm2java
 */
public class Alerta  implements java.io.Serializable {


     private Integer idalerta;
     private Usuario usuario;
     private Date loghora;
     private double longitude;
     private double latitude;
     private String tipo;

    public Alerta() {
    }

    public Alerta(Usuario usuario, Date loghora, double longitude, double latitude, String tipo) {
       this.usuario = usuario;
       this.loghora = loghora;
       this.longitude = longitude;
       this.latitude = latitude;
       this.tipo = tipo;
    }
   
    public Integer getIdalerta() {
        return this.idalerta;
    }
    
    public void setIdalerta(Integer idalerta) {
        this.idalerta = idalerta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getLoghora() {
        return this.loghora;
    }
    
    public void setLoghora(Date loghora) {
        this.loghora = loghora;
    }
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


