package hibernate;
// Generated 21/10/2016 21:23:46 by Hibernate Tools 4.3.1



/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private Integer idendereco;
     private Usuario usuario;
     private double longitude;
     private double latitude;
     private String tiporesidencia;

    public Endereco() {
    }

    public Endereco(Usuario usuario, double longitude, double latitude, String tiporesidencia) {
       this.usuario = usuario;
       this.longitude = longitude;
       this.latitude = latitude;
       this.tiporesidencia = tiporesidencia;
    }
   
    public Integer getIdendereco() {
        return this.idendereco;
    }
    
    public void setIdendereco(Integer idendereco) {
        this.idendereco = idendereco;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }
    public String getTiporesidencia() {
        return this.tiporesidencia;
    }
    
    public void setTiporesidencia(String tiporesidencia) {
        this.tiporesidencia = tiporesidencia;
    }




}


