package hibernate;
// Generated 21/10/2016 21:23:46 by Hibernate Tools 4.3.1



/**
 * Seguranca generated by hbm2java
 */
public class Seguranca  implements java.io.Serializable {


     private Integer idseguranca;
     private Usuario usuario;
     private double hash;
     private String password;
     private String copare;

    public Seguranca() {
    }

    public Seguranca(Usuario usuario, double hash, String password, String copare) {
       this.usuario = usuario;
       this.hash = hash;
       this.password = password;
       this.copare = copare;
    }
   
    public Integer getIdseguranca() {
        return this.idseguranca;
    }
    
    public void setIdseguranca(Integer idseguranca) {
        this.idseguranca = idseguranca;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public double getHash() {
        return this.hash;
    }
    
    public void setHash(double hash) {
        this.hash = hash;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCopare() {
        return this.copare;
    }
    
    public void setCopare(String copare) {
        this.copare = copare;
    }




}


